### ISSUE TITLE
[Feature] Prisma ?

### ISSUE THREAD

**Issue by Klayvann** [barthofu/tscord#126]
### Feature

Do you plan to add Prisma to your project? Because I can't do without it xD.

**Comment by barthofu** [comment]
Hey! 

![image](https://github.com/barthofu/tscord/assets/66025667/03ae358f-6877-4870-ae2b-9f4e5a4f9378)

tl;dr: we are planning to dig that and make an alternative variant _if it is possible_ using prisma instead of mikro-orm.
