### ISSUE TITLE
[Bug] isJSONEncodable is not a function

### ISSUE THREAD

**Issue by Nik-Novak** [barthofu/tscord#139]
### What happened?

1) Clone repo
2) yarn install; yarn dev

$ cross-env NODE_ENV=development nodemon --exec node -r @swc-node/register src/main.ts
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `node -r @swc-node/register src/main.ts`
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'en' ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'en' completed
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'fr' ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'fr' completed
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'ru' ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'ru' completed
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'uk' ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'uk' completed
info [09/01/2024 - 10:45:58] [typesafe-i18n], updating types ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], updating types completed

error [09/01/2024 - 10:46:00] (ERROR) Unhandled rejection : isJSONEncodable is not a function
        > /home/dev/projects/MindKnight/tscord/node_modules/discord.js/src/managers/ApplicationCommandManager.js:234
        > /home/dev/projects/MindKnight/tscord/node_modules/discord.js/src/managers/ApplicationCommandManager.js:174
        > <anonymous>:null
        > /home/dev/projects/MindKnight/tscord/node_modules/discord.js/src/managers/ApplicationCommandManager.js:174
        > /home/dev/projects/MindKnight/tscord/node_modules/discordx/src/Client.ts:747
        > node:internal/process/task_queues:95
        > /home/dev/projects/MindKnight/tscord/node_modules/discordx/src/Client.ts:581
        > /home/dev/projects/MindKnight/tscord/src/events/ready.ts:31

### Reproduction

main repo Jan 9 2024

### Relevant log output

```Shell
1) Clone repo
2) yarn install; yarn dev

$ cross-env NODE_ENV=development nodemon --exec node -r @swc-node/register src/main.ts
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `node -r @swc-node/register src/main.ts`
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'en' ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'en' completed
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'fr' ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'fr' completed
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'ru' ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'ru' completed
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'uk' ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], importing translations for locale 'uk' completed
info [09/01/2024 - 10:45:58] [typesafe-i18n], updating types ...
info [09/01/2024 - 10:45:58] [typesafe-i18n], updating types completed


error [09/01/2024 - 10:46:00] (ERROR) Unhandled rejection : isJSONEncodable is not a function
        > /home/dev/projects/MindKnight/tscord/node_modules/discord.js/src/managers/ApplicationCommandManager.js:234
        > /home/dev/projects/MindKnight/tscord/node_modules/discord.js/src/managers/ApplicationCommandManager.js:174
        > <anonymous>:null
        > /home/dev/projects/MindKnight/tscord/node_modules/discord.js/src/managers/ApplicationCommandManager.js:174
        > /home/dev/projects/MindKnight/tscord/node_modules/discordx/src/Client.ts:747
        > node:internal/process/task_queues:95
        > /home/dev/projects/MindKnight/tscord/node_modules/discordx/src/Client.ts:581
        > /home/dev/projects/MindKnight/tscord/src/events/ready.ts:31
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nik-Novak** [comment]
ubuntu 22.04, node 20.10.0

**Comment by barthofu** [comment]
Hey!

There is currently problems with the latest Node LTS (20.10.0), maybe using the v18 should fix the problem.

These problems will be adressed in the future release of TSCord !

**Comment by barthofu** [comment]
Fixed in https://github.com/barthofu/tscord/pull/155
