### ISSUE TITLE
[Feature] Automatic upload of SQLite backups to a cloud provider

### ISSUE THREAD

**Issue by barthofu** [barthofu/tscord#17]
### Feature?

SQLite backups could be automaticaly uploaded to a cloud provider such as [MEGA](https://mega.io/), Google Drive, etc.

**Comment by astahmer** [comment]
you might like this https://github.com/benbjohnson/litestream

**Comment by barthofu** [comment]
> you might like this https://github.com/benbjohnson/litestream

really interesting indeed!

**Comment by barthofu** [comment]
Moved to https://github.com/barthofu/tscord-plugins/issues/18
