### ISSUE TITLE
[Feature] "Add to server" button

### ISSUE THREAD

**Issue by AirOne01** [barthofu/tscord#68]
### Feature?

Use the "Add to server" button by default

Example here with the Tatsumaki bot:

![Add to server button](https://user-images.githubusercontent.com/21955960/189869597-8c22af9a-b899-4668-b88d-94326a34103f.png)

**Comment by Mr-Artemus** [comment]
If I'm not mistaken, this button can only be configured from the [Discord developers interface](https://discord.com/developers/applications).
Steps to activate it: 
1. Choose your application
2. Select **OAuth2** on the left bar
3. Into the **Default Authorization Link** section, select **In-app Authorization**
4. Check both boxes
5. Choose the default permissions
6. Save
