### ISSUE TITLE
[Bug] Can't install deps

### ISSUE THREAD

**Issue by AirOne01** [barthofu/tscord#97]
### What happened?

Cannot install deps. It said node-gyp and sqlite so i figured i might just ask here.

[![asciicast](https://asciinema.org/a/yqAfJHENogzuiPg2rt7TUxGXr.svg)](https://asciinema.org/a/yqAfJHENogzuiPg2rt7TUxGXr)

### Reproduction

`npm i`
`pnpm i`

### Relevant log output

```Shell
https://asciinema.org/a/yqAfJHENogzuiPg2rt7TUxGXr
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by barthofu** [comment]
what is your OS and node / npm versions?

**Comment by AirOne01** [comment]
> what is your OS and node / npm versions?

Using Archlinux (kernel `6.0.8-arch1-1`)
Python `3.10.8`
Node `v19.0.0`
npm `8.19.2`
pnpm `7.14.0`
yarn `1.22.19`

**Comment by AirOne01** [comment]
It may be a problem with my python3 install, I'm trying to figure it out on my own

**Comment by AirOne01** [comment]
Works normally in Codespaces instance. I'm just gonna drop this issue and continue there.
